[package]
name = "s9_kafka_sink"
version = "0.1.0"
edition = "2021"
authors = ["Alexander Silvennoinen <alex@silvennoinen.de>"]

[lib]
name = "s9_kafka_sink"
path = "src/lib.rs"

[dependencies]
rdkafka = "0.38"